name: api hamp build
on:
  workflow_dispatch:

jobs:
  get-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)
      - name: tag
        run: echo ${{ steps.tag.outputs.tag }}
