name: api hamp build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-docker-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0
      - name: Incrementar versión del tag
        id: get-tag
        run: |
          VERSION=$(git describe --abbrev=0)
          echo "version:  $VERSION"
          MAJOR=$(echo $VERSION | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo $VERSION | cut -d. -f2 | sed 's/^0*//')
          NEW_MINOR=$(expr $MINOR + 1)
          NEW_VERSION="$MAJOR.$(printf $NEW_MINOR).0"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: hampcl/api-hamp:${{ steps.get-tag.outputs.new_version }},hampcl/api-hamp:latest
          
      - name: Create Tags
        run: |
          git config --global user.email "github@hamp.cl"
          git config --global user.name "Hamp Github Actions"
          git tag -a v${{ steps.get-tag.outputs.new_version }} -m "Versión ${{ steps.get-tag.outputs.new_version }}"
          git push --tags
