name: api hamp build
on:
  push:
    branches:
      - master

jobs:
  get-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         fetch-depth: 0
      - name: Incrementar versión del tag
        id: get-tag
        run: |
          VERSION=$(git describe --abbrev=0)
          echo "version:  $VERSION"
          MAJOR=$(echo $VERSION | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo $VERSION | cut -d. -f2 | sed 's/^0*//')
          NEW_MINOR=$(expr $MINOR + 1)
          NEW_VERSION="v$MAJOR.$(printf $NEW_MINOR).0"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          
      - name: create docker image
        id: create-docker
        run: echo ${{ steps.get-tag.outputs.new_version }}
