name: api hamp build
on:
  workflow_dispatch:

jobs:
  get-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Incrementar versión del tag
        id: get-tag
        run: |
          VERSION=$(git describe --abbrev=0)
          MAJOR=$(echo $VERSION | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo $VERSION | cut -d. -f2 | sed 's/^0*//')
          NEW_MINOR=$(expr $MINOR + 1)
          NEW_VERSION="v$MAJOR.$(printf "%02d" $NEW_MINOR).0"
          echo "::set-output name=new_version::$NEW_VERSION"
      - name: tag
        run: echo ==== ${{ steps.get-tag.outputs.new_version }}
