name: api hamp build
on:
  workflow_dispatch:

jobs:
  get-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Incrementar versión del tag
        id: get-tag
        run: |
          VERSION=$(git describe --abbrev=0)
          MAJOR=$(echo $VERSION | cut -d. -f1 | sed 's/v//')
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          NEW_VERSION="v$MAJOR.$(expr $MINOR + 1).0"
          echo "name=new_version::$NEW_VERSION" >> $GITHUB_OUTPUT
      - name: tag
        run: echo ==== ${{ steps.get-tag.outputs.new_version }}
